# Generated by Django 4.2.7 on 2025-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_jobexperience_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_api',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
