# Generated by Django 4.2.7 on 2025-04-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_portfolio_is_api_portfolio_is_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tier',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
    ]
