# Generated by Django 4.2.7 on 2025-04-08 18:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_portfolio_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('SUPERVISED_LEARNING', 'Supervised Learning'), ('UNSUPERVISED_LEARNING', 'Unsupervised Learning'), ('REINFORCEMENT_LEARNING', 'Reinforcement Learning'), ('DEEP_LEARNING', 'Deep Learning'), ('NATURAL_LANGUAGE_PROCESSING', 'Natural Language Processing'), ('COMPUTER_VISION', 'Computer Vision'), ('TIME_SERIES', 'Time Series Analysis'), ('RECOMMENDATION_SYSTEMS', 'Recommendation Systems'), ('ANOMALY_DETECTION', 'Anomaly Detection'), ('CLUSTERING', 'Clustering')], default='SUPERVISED_LEARNING', max_length=264)),
                ('tier', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B')], default='A', max_length=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ml_models')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='ml_models', to='main.skill')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['name'],
            },
        ),
    ]
