# Generated by Django 4.2.7 on 2025-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mlmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
