# Generated by Django 4.2.7 on 2025-06-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
