# Generated by Django 4.2.7 on 2025-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_award_issued_by_alter_certificate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
