# Generated by Django 4.2.7 on 2025-07-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_portfolio_body_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='body_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='name_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
