# Generated by Django 4.2.7 on 2025-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_mlmodel_body_embedding_mlmodel_name_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
