# Generated by Django 4.2.7 on 2025-07-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_project_body_embedding_project_description_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='name_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
