# Generated by Django 4.2.7 on 2025-07-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_blog_body_embedding_blog_description_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='category',
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
