# Generated by Django 4.2.7 on 2025-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_certificate_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='title_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
