# Generated by Django 4.2.7 on 2025-07-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_award_description_embedding_award_title_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='company_name_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='description_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='job_title_embedding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='location_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
